# -*- coding: utf-8 -*-
"""Customer feedback analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvOKVFJHGKcAtcLqRtRnSkYbxshiPCPW
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Dummy feedback data
data = {
    'Theme': ['Delivery', 'Product Quality', 'Customer Service', 'Pricing', 'Packaging'],
    'Mentions': [12, 18, 10, 7, 5],
    'Avg_CSAT': [2.5, 4.6, 3.0, 4.2, 1.8]
}

df = pd.DataFrame(data)

# Bar chart for feedback themes
fig1 = px.bar(df, x='Theme', y='Mentions', title="Feedback Mentions by Theme", color='Theme')

# CSAT scores by theme
fig2 = px.line(df, x='Theme', y='Avg_CSAT', title="Average CSAT by Theme", markers=True)

# Combine charts
fig = go.Figure(data=fig1.data + fig2.data)
fig.update_layout(title="Customer Feedback Dashboard", yaxis_title="Mentions / CSAT Score")
fig.show()